stages:
  - install
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .npm
    - core/target/

install_front:
  stage: install
  image: szofttech.inf.elte.hu:5050/szofttech-c-2025/group-08/vitorlas-devs:custom
  variables:
    npm_config_cache: .npm
  script:
    - npm i --prefer-offline
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour

build_app:
  stage: build
  image: szofttech.inf.elte.hu:5050/szofttech-c-2025/group-08/vitorlas-devs:custom
  variables:
    npm_config_cache: .npm
  script:
    - npm run tauri build -- -t x86_64-pc-windows-msvc
  dependencies:
    - install_front
  artifacts:
    paths:
      - core/target/x86_64-pc-windows-msvc/release/safari.exe
    expire_in: 1 week
    name: safari-windows-x86_64
