stages:
  - image
  - install
  - build

variables:
  DOCKER_TLS_CERTDIR: ''

build_custom_image:
  stage: image
  image: docker:latest
  services:
    - name: docker:24.0.7-dind
      alias: docker
  script:
    - unset DOCKER_HOST
    - sudo docker build -t $CI_REGISTRY_IMAGE:custom .
    - sudo docker push $CI_REGISTRY_IMAGE:custom

image: $CI_REGISTRY_IMAGE:custom

cache:
  paths:
    - node_modules/
    - core/target/

install_front:
  stage: install
  script:
    - bun install

build_app:
  stage: build
  script:
    - bun run tauri build
