stages:
  - install
  - build

install_front:
  stage: install
  image: szofttech.inf.elte.hu:5050/szofttech-c-2025/group-08/vitorlas-devs:custom
  script:
    - bun install

build_app:
  stage: build
  image: szofttech.inf.elte.hu:5050/szofttech-c-2025/group-08/vitorlas-devs:custom
  script:
    - bun run tauri build
