image: docker:latest

services:
  - name: docker:24.0.7-dind
    alias: docker

variables:
  DOCKER_HOST: ''
  DOCKER_TLS_CERTDIR: ''

stages:
  - image
  - install
  - build

build_custom_image:
  stage: image
  script:
    - docker build -t $CI_REGISTRY_IMAGE:custom .
    - docker push $CI_REGISTRY_IMAGE:custom

install_front:
  stage: install
  script:
    - bun install

build_app:
  stage: build
  script:
    - bun run tauri build
